# Name of workflow
name: CI

on:
  - push

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js @latest
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Run linter
        run: make lint
